### ISSUE TITLE
AlwaysOn cannot be set for this site as the plan does not allow it.

### ISSUE THREAD

**Issue by zedy-wj** [Azure-Samples/azd-simple-flask-appservice#1]
**Describe the issue:**
`AlwaysOn` cannot be set for this site because it uses the `F1 (free) SKU` for app service. There will be a conflict.

**Repro Steps:**
1. Execute command `azd up -t tonybaloney/simple-flask-azd`, and you will see the error as below:
![image](https://user-images.githubusercontent.com/81678720/221077193-3d285db3-316b-403f-9818-7c689e32c18f.png)

**Environments:**

- OS: windows .
- Template: https://github.com/tonybaloney/simple-flask-azd
- Branch: master
- Azd version: azd version 0.6.0-beta.2 (commit c4a201e55a13eba77f9037b296a90e0f81b00dbe)

**Suggestion:**
Please upgrade the `SKU` for app service or set `AlwaysOn` to `false`.

**Expected behavior:**
Execute command `azd up -t tonybaloney/simple-flask-azd` successfully.

@tonybaloney for notification.

**Comment by tonybaloney** [comment]
Oh good catch. I changed the SKu at the last moment

**Comment by zedy-wj** [comment]
@tonybaloney - Do you want to replace available `SKU`, or let users change `SKU` themselves each time?

**Comment by tonybaloney** [comment]
I've removed the flag

**Comment by zedy-wj** [comment]
Okay, we will close this issue, thanks!
